name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  release:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN || '' }}
        run: pnpm dlx semantic-release
